<?php

/**
 * Implements hook_theme().
 */
function bt_custom_theme() {
    return [
        'bt_custom_simple_form' => [
            'render element' => 'form',
            'template' => 'simple-form',
        ],
        'bt_custom_simple_page' => [
            'render element' => 'elements',
            'template' => 'simple-page',
        ],
    ];
}

/**
 * Implements hook_preprocess_bt_custom_view().
 */
/*function bt_custom_preprocess_bt_custom_view(&$variables) {
    //kint($variables);
    $item = &$variables['elements']['bt_custom']['#value'];
    $variables['title'] = $item->title;
    $variables['price'] = $item->price;
    $variables['sku'] = $item->sku;
    $variables['ajax_link'] = $variables['elements']['ajax_link'];
    $variables['extra_values'] = array( 'key1' => t('Item 1'),
                                        'key2' => t('Item 2'),
                                        'key3' => t('Item 3'));
}*/