bt_card.settings:
  type: config_object
  label: 'BT Card Settings'
  mapping:
    cards_per_page:
      type: number
      label: 'Cards per page'
    help_message:
      type: label
      label: 'Help message for user'